### ISSUE TITLE
A few small issues getting started

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#1]
I needed to 
pip install BeautifulSoup4

WARNING: Unable to find `/images/k2/CampaignSkyII.png`, skipping url replacement.

For the first I guess add this to the installation instructions (perhaps include all required modules)
For the second you probably need to push that file

**Comment by barentsen** [comment]
Fixed!

I have pushed `/images/k2/CampaignSkyII.png` and updated the `README`.
