### ISSUE TITLE
Update the position of C13

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/KeplerScienceWebsite#10]
Make sure we update the coordinates listed in `content/pages/k2-observing/k2-campaign-fields.md` once C13 is fixed.

**Comment by kcolon** [comment]
And make sure to remove or update coordinates on old website!

**Comment by mrtommyb** [comment]
We should update for now I think. We should also make sure that the Cycle 4 NRA have links to the new site in.
In addition, I note that http://keplergo.github.io/KeplerScienceWebsite/k2-proposing-targets.html#solicitations lists C13 as set.

**Comment by kcolon** [comment]
The C13 coordinates have already been updated to the latest version on both the old and new site (and according to Fergal the field was close to being finalized today...maybe this will be set by Friday?).

**Comment by barentsen** [comment]
C13 was fixed yesterday:

```
Final FOV choice is: 
FOV date is 2017 APR 27 18:28:16 UTC 
Proposed C13 coordinates are: 
   RA = 72.7968465 
   Dec = 20.7863018 
   Roll = -172.6384788 
  (all in degrees) 

Possible observing dates are 3/6/17 to 5/27/17 
Requested observing dates are 3/8/17 to 5/27/17 
```

**Comment by barentsen** [comment]
I updated `k2-campaign-fields.md` to reflect the new coordinates.

Still to do:
- [ ] someone to double-check conversion to sexagesimal;
- [ ] update old website;
- [ ] update K2fov.

**Comment by barentsen** [comment]
@kcolon has verified that the sexagesimal coordinates are correct, and @barentsen has updated the old website and updated K2fov. Closing this issue!
