### ISSUE TITLE
Port PyKE task and tutorial pages

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#14]
- individual PyKE task pages
- PyKE tutorial pages

**Comment by barentsen** [comment]
I have added a .htaccess file to the webserver which redirects /K2/index.shtml to /index.html, so the Google search results point straight to the new website now.

**Comment by mrtommyb** [comment]
We should probably move the index to index_old.shtml so it is accessible.

**Comment by barentsen** [comment]
Good idea, done: http://keplerscience.arc.nasa.gov/K2/index_old.shtml

**Comment by barentsen** [comment]
PyKE tasks and tutorials are now part of the new PyKE3 docs at pyke.readthedocs.io, so we can close this issue!
