### ISSUE TITLE
Need new icon for Kepler spacecraft

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#15]

**Comment by barentsen** [comment]
I removed the $!**! antenna from the icon font.  I hope it will still work on older browsers.  Closing issue.

**Comment by kcolon** [comment]
Might not work on Safari (and other browsers?).  Tom or others should check this.

**Comment by barentsen** [comment]
A funky new icon (with proper antenna) has been created and pushed to the repository.

Cannot sync to webserver because my vpn workaround is b0rked.

**Comment by barentsen** [comment]
Fancy new icon is now online!
