### ISSUE TITLE
Need abstract for GO4901 (DDT proposal)

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#16]

**Comment by kcolon** [comment]
@mrtommyb

**Comment by mrtommyb** [comment]
Attaching [DDT_White_C4.pdf](https://github.com/KeplerGO/KeplerScienceWebsite/files/22039/DDT_White_C4.pdf)

**Comment by kcolon** [comment]
Done! Added abstract to site.
