### ISSUE TITLE
Add VARTOOLS to Other Software

### ISSUE THREAD

**Issue by JeffLCoughlin** [KeplerGO/KeplerScienceWebsite#163]
https://www.astro.princeton.edu/~jhartman/vartools.html

VARTOOLS is very similar to lightcurve in functionality. Just command-line and C based.

**Comment by barentsen** [comment]
Thanks for noticing!  VARTOOLS is a fantastic package and I promptly added it to the "other software" listing (cf. https://github.com/KeplerGO/lightkurve/commit/bfa7db55a6c2f176677428703ddd6292cf127dd9 )
