### ISSUE TITLE
Beef up the K2 section on the "Science" page

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/KeplerScienceWebsite#18]
@christopherburke has rightly pointed out that the K2 section on the "science" page is very sparse compared to Kepler, i.e. here:

     http://keplergo.github.io/KeplerScienceWebsite/the-science.html#science-from-k2

We should figure out a way to beef this up.

**Comment by kcolon** [comment]
It appears sparse partly because I didn't know where else to put the WG, GO, and PSP programs for Kepler.  But I agree we could add more, to both the Kepler and K2 side.

**Comment by kcolon** [comment]
Pushed a revision to the science page.
