### ISSUE TITLE
Add pictures of our faces to the helpdesk page

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/KeplerScienceWebsite#19]
So that people at conferences can recognize us.

For Knicole, use facebook picture.
Tom will send his.
Geert will send his.

**Comment by barentsen** [comment]
Faces have been added.

**Comment by mirca** [comment]
@gully add your face gully =)

**Comment by gully** [comment]
Closed in abaf24ee2b1c6c42854b2763a17dfa68d3f7ac38

**Comment by mirca** [comment]
Add your face, @rawien =D

**Comment by mirca** [comment]
@rawien check an example here: https://github.com/KeplerGO/KeplerScienceWebsite/pull/102 =D

**Comment by rawien** [comment]
![image](https://user-images.githubusercontent.com/14965634/27925495-c45b0808-6239-11e7-9eb0-cd71d548259e.png)
Here's the photo! Thanks for editing it for me Ze <3
