### ISSUE TITLE
Have a launch party

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#27]
![image](https://cloud.githubusercontent.com/assets/1900573/10810558/6620c788-7dbf-11e5-9eec-1acc84eb9d00.png)

**Comment by barentsen** [comment]
@mrtommyb @kcolon The new website is now live.

The index page of the old website has been preserved at http://keplerscience.arc.nasa.gov/index_old.shtml

To update the new website on the server, I use a script that says:
```
make clean
make html
rsync -avzP output/* USERNAME@HOST:/var/www/docs/keplergo/
```

@mrtommyb Where is the party?

**Comment by mrtommyb** [comment]
Assigning to Knicole as chief party planner.

**Comment by barentsen** [comment]
:+1:

**Comment by kcolon** [comment]
party tonight in Santa Barbara?

**Comment by mrtommyb** [comment]
Ok...

**Comment by mrtommyb** [comment]
What are we doing tonight?

**Comment by kcolon** [comment]
Poster sess is @ 5 pm...includes one free drink!

**Comment by barentsen** [comment]
Any progress on this issue?

**Comment by mrtommyb** [comment]
All happiness in the world is canceled until the Senior Review proposal is submitted.

**Comment by kcolon** [comment]
:-( 

Launch party at AAS?

**Comment by mrtommyb** [comment]
This issue is still open. I'm assigning to @mshabram to plan and execute.

**Comment by mrtommyb** [comment]
Apparently I can't assign to someone outside the organization. It's still @mshabram job to organize though.

**Comment by mshabram** [comment]
How many Launch parties have y'all had?

**Comment by kcolon** [comment]
Zero!

**Comment by mshabram** [comment]
What are you launching? lol

**Comment by kcolon** [comment]
We launched the new website… back on November 1st haha

**Comment by mshabram** [comment]
Awwe I see, PARTY TIME!!!!

**Comment by barentsen** [comment]
Can someone report on the status of this ticket?

**Comment by barentsen** [comment]
We missed the launch party window.
