### ISSUE TITLE
Have Jeff Coughlin write blog post about Kepler occurrence rate products

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#29]

**Comment by mrtommyb** [comment]
@kcolon @barentsen is this still relevant. Should be poke mike again?

**Comment by barentsen** [comment]
Will the DR25 products be identical/similar, or should we wait for them?

**Comment by JeffLCoughlin** [comment]
Just came across this one. I'll assign to myself. May be relevant again with the DR25 supplemental KOIs and Product overview going out to the archives by end of this month.
