### ISSUE TITLE
Add the Kepler FOV on the front page banner

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/KeplerScienceWebsite#30]

**Comment by barentsen** [comment]
Someone needs to ask Wendy.

**Comment by kcolon** [comment]
I vote Tom asks.

**Comment by mrtommyb** [comment]
I can but I need the slackers to finish watching the movie

**Comment by kcolon** [comment]
I guess you'll have to wait a couple hours then!

**Comment by barentsen** [comment]
Done.

**Comment by mrtommyb** [comment]
Have we now officially launched?
