### ISSUE TITLE
Blog post to announce C5 data release

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#34]
We should also send out an email blast this this information

**Comment by barentsen** [comment]
Wanted to do this on Saturday, but decided to wait for data release notes and MAST's official announcement. Does that sound right?

**Comment by mrtommyb** [comment]
This sounds right. We should do it now though

**Comment by barentsen** [comment]
I wrote one.  Will push after lunch.

**Comment by barentsen** [comment]
New article about C5 data release posted and synced to web.
