### ISSUE TITLE
Add dev banner to gh-pages branch?

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/KeplerScienceWebsite#37]
We should consider deleting the development copy hosted at

    http://keplergo.github.io/KeplerScienceWebsite

To avoid having a second, outdated copy of the website on the interwebs.

Any reason to keep it?

**Comment by mrtommyb** [comment]
I think there is value in being able to have a draft website online to allow us to circulate changes. We should switch the dev banner on again though.

**Comment by barentsen** [comment]
The red warning banner gets added automatically when typing `make github` now.
