### ISSUE TITLE
Add K2 footprints in KML format to the website

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#38]
I received two requests for this today! Note the Kepler FOV table is found on this page: http://keplerscience.arc.nasa.gov/the-kepler-space-telescope.html#field-of-view

An alternative addition might be to include the roll angle in the fields table.

**Comment by barentsen** [comment]
K2 footprint details (corners of all channels) have been added in JSON and CSV format to the "K2 Fields" page on the website.  @knicole please inform whoever requested you.

Now looking into also providing MOC and KML files for the footprints.

**Comment by kcolon** [comment]
Thanks @barentsen ! Now I just have to remember who asked me ... :)

**Comment by kcolon** [comment]
Can this be closed as per http://keplerscience.arc.nasa.gov/k2-fields.html#moc-files ?

**Comment by barentsen** [comment]
I haven't done KML files yet.  Let's change the title of this issue to reflect that and leave it open.
