### ISSUE TITLE
Update C4 data release notes

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#44]
Susan changed something on this page on 11/06 - http://keplerscience.arc.nasa.gov/K2/C4drn.shtml so we need to make sure our new site has the latest update

**Comment by barentsen** [comment]
@mustaric Can you give us a pointer as to what has changed?

**Comment by mustaric** [comment]
I haven’t changed it yet.  Still on my computer.  I’ve added a link to a file. I can show you on Monday.

Susan

On Nov 6, 2015, at 5:08 PM, Geert Barentsen <notifications@github.com> wrote:

> @mustaric Can you give us a pointer as to what has changed?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

---
"I love deadlines. I like the whooshing sound they make as they fly by." -- Douglas Adams
