### ISSUE TITLE
Add Kepler mission clock to front page

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#46]
Following the footsteps of the KASOC (http://kasoc.phys.au.dk/)

I thought this would be awesome :-)

**Comment by mrtommyb** [comment]
Good idea! I support this. We could also try to count K2 but it's not so clear when the zeropoint is

**Comment by barentsen** [comment]
There's some place in the footer.  Not sure it warrants prime screen real estate?

A clock counting the days into the current campaign, or a countdown clock to the next campaign or data release, may be more useful?

**Comment by mrtommyb** [comment]
Perhaps add a Kepler mission clock to this page 
http://keplergo.github.io/KeplerScienceWebsite/objectives.html

**Comment by kcolon** [comment]
Yeah, maybe a clock counting the days into or left in the current campaign!

It’s fun knowing the days since Kepler launched, but it’s not as informative I suppose :)

**Comment by barentsen** [comment]
Proposing to cancel the mission clock idea, unless someone wants to work on that.
