### ISSUE TITLE
Update C10-C13 science run dates

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#48]
C6 data now delivering ~ 1/21/16

Check KACR for latest science run dates

**Comment by mrtommyb** [comment]
why is there a delay to C6 delivery?

**Comment by kcolon** [comment]
I think they pushed it because of the holidays, but apparently the schedule is a mess right now so they need a few days to sort out the schedule and confirm a realistic delivery date.

**Comment by mrtommyb** [comment]
Understood. Thanks for the update. When we have fully revised dates we should put out a blog post

**Comment by kcolon** [comment]
I think we can close this but do we need a blog post for any reason?

**Comment by kcolon** [comment]
I'm closing this (unless someone says otherwise and wants to reopen).  I have also updated the C6 data delivery date to now Feb 9 (new expected date).
