### ISSUE TITLE
Pull in the latest kepler blog posts

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#5]
I also need a way to link to one of these blog posts from the data release page because the only place that one of the products is documented in on a blog post

**Comment by barentsen** [comment]
I copied and committed all the latest blog posts two days ago, so this should be ok.  However let's keep this issue open so we remember to do it before going live.

You can link directly to a blog post using the relative html url for now.

**Comment by mrtommyb** [comment]
It's still not fixed

**Comment by barentsen** [comment]
Can you refresh?   I'm definitely seeing the 3 new blog posts now at http://keplergo.github.io/KeplerScienceWebsite/

I did a `make github` which didn't do the update.

Then I did a `make devserver`, checked that the blog posts showed up on localhost, and then `make github` did magically update the github.io website.

**Comment by mrtommyb** [comment]
Geert Finally fixed this so we can close

**Comment by barentsen** [comment]
re-opening because it got milestone "before-going-live"

**Comment by mrtommyb** [comment]
Can we close this?

**Comment by barentsen** [comment]
Yes, all posts from the old blog are on the new website. Closing.
