### ISSUE TITLE
Consider: is the long DRN page confusing?

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/KeplerScienceWebsite#51]
Mike H. complained it's unclear what campaign a section of text belongs to.

**Comment by mrtommyb** [comment]
I guess we could consider having the "K2 Campaign 5" title stay at the top of the page when you scroll down and then move onto the next title when you scroll past

**Comment by barentsen** [comment]
Do you think I can do that?

**Comment by mrtommyb** [comment]
Firstly we should fix the indentation issue.
Compare 
http://keplerscience.arc.nasa.gov/k2-data-release-notes.html#k2-campaign-2
with 
http://keplerscience.arc.nasa.gov/k2-data-release-notes.html#k2-campaign-3

**Comment by barentsen** [comment]
How did you even spot that?

I'm tempted to split the DRN over separate pages again, as it will be easier for the A.A.S. as well, but let's sleep over it for a few nights.

**Comment by barentsen** [comment]
I like the K2 DRN being on one page.  Given that there have been no complaints about it for the past few campaigns, I'm closing this.
