### ISSUE TITLE
Finish porting all pages relevant to proposal submission

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#55]
E.g. http://keplerscience.arc.nasa.gov/K2/ProposalPreparationTargetTable.shtml and others!

**Comment by mrtommyb** [comment]
This page is currently wrong. It needs fixing now.
http://keplerscience.arc.nasa.gov/k2-proposing-targets.html

**Comment by mrtommyb** [comment]
@barentsen @kcolon let's get this fixed today

**Comment by mrtommyb** [comment]
Things that are wrong:
Availability of funds section.

**Comment by mrtommyb** [comment]
We also need a blog post for this

**Comment by kcolon** [comment]
main content is updated and the section headings revised a bit, but still need to add info from http://keplerscience.arc.nasa.gov/K2/ProposalPreparationTargetTable.shtml and http://keplerscience.arc.nasa.gov/K2/ProposalPreparationContent.shtml 

will do this tonight!

**Comment by mrtommyb** [comment]
great

**Comment by kcolon** [comment]
all content has been ported -- let me know if you see anything amiss @ http://keplerscience.arc.nasa.gov/k2-proposing-targets.html

**Comment by mrtommyb** [comment]
thanks!
