### ISSUE TITLE
Fix dead link to http://keplerscience.arc.nasa.gov/k2-photometric-performance.html#photometric-performance

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#57]
Per email:
From: tlhackque <tlhackque@yahoo.com>
Subject: Dead link on kepler website
Date: November 26, 2015 at 12:32:07 PM PST
To: <keplergo@mail.arc.nasa.gov>

http://keplerscience.arc.nasa.gov/k2-photometric-performance.html#photometric-performance is a dead link,
which is referenced from http://keplerscience.arc.nasa.gov/objectives.html

The referral is under the heading "K2", and is under the text "approaching that of the original Kepler mission"

**Comment by mrtommyb** [comment]
I have fixed the link on http://keplerscience.arc.nasa.gov/objectives.html with 6bf20be

**Comment by mrtommyb** [comment]
I found a couple of other dead links and fixed them too with 8a6d7c3
@barentsen can you push this to the live site and then close

**Comment by barentsen** [comment]
Live site has been updated.
