### ISSUE TITLE
Write blog post for K2 Cycle 4 NRA

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#58]

**Comment by kcolon** [comment]
How's this?
https://github.com/KeplerGO/KeplerScienceWebsite/blob/master/content/news/Cycle4.md

**Comment by barentsen** [comment]
Can we say "Campaigns 11 12 13" in the title rather than "Cycle 4", to make the title more informative?

**Comment by barentsen** [comment]
Nitpicking: should the deadline times be in ET instead of EST?

**Comment by kcolon** [comment]
How about "Call for K2 GO Cycle 4 Proposals for Campaigns 11, 12, and 13"?

**Comment by kcolon** [comment]
It is EST currently so I think it's safe to say that. (daylight savings time begins March 13)

**Comment by barentsen** [comment]
Ohhh, I thought the "S" in EST stood for summer. Never mind! I'm st000p1d :-)

**Comment by barentsen** [comment]
:+1:

**Comment by barentsen** [comment]
(My confusion is due to BST = British Summer Time)

**Comment by kcolon** [comment]
Oh, well that's funny :-)  Other non-Americans may be confused as well... should I write out EST as Eastern Standard Time?

**Comment by barentsen** [comment]
Nah don't worry. I think you can close this!

**Comment by kcolon** [comment]
done!
