### ISSUE TITLE
Add in the google analytics script when we go live 

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#6]
When the site goes live at keplerscience.arc.nasa.gov we should include the following script for tracking purposes. I don't think we should put it into the dev site though

```html
<script language="javascript" id="_fed_an_ua_tag" src="//dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=NASA"></script>
```

**Comment by mrtommyb** [comment]
We should probably include the subagency too and also demographics tracking
```html
<script language="javascript" id="_fed_an_ua_tag" src="//dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=NASA&subagency=ARC&dclink=true"></script>
```

**Comment by barentsen** [comment]
The variable `ANALYTICS` in `pelicanconf.py` is now used to specify these scripts.

The scripts are included in the output of every page once the variable `DEVMODE` is set to `False`.  (This variable also controls whether or not the red warning banner at the top is shown.)
