### ISSUE TITLE
A large file makes pushing the website take too long

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#60]
Can we find a way to fix this? Why is this file being pushed every time? Can we tell it to keep the current version?

**Comment by kcolon** [comment]
Is there a specific you know is causing an issue? I agree it'd be nice not to have to push every file every time, if they aren't changed.

**Comment by barentsen** [comment]
Apparently it's the .DS_STORE directories that OSX likes to create.

**Comment by barentsen** [comment]
I can see no more .DS_STORE in the repository.  Closing this.
