### ISSUE TITLE
C8 target list contains a lot of (ra, dec) = (0, 0) values

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/KeplerScienceWebsite#62]
@mrtommyb Can you fix this?

**Comment by kcolon** [comment]
can we close this?

**Comment by barentsen** [comment]
This is not fixed yet. `content/data/campaigns/c8/K2Campaign8targets.csv` contains NaNs and 0s in funny places.  I believe @mrtommyb has a correct version on his laptop though.

**Comment by mrtommyb** [comment]
I push the corrected version. Could you check it and close this issue

**Comment by barentsen** [comment]
The new version looks great. Best xmas gift ever! :christmas_tree: :santa:

Closing issue.
