### ISSUE TITLE
DRN Table of Contents

### ISSUE THREAD

**Issue by mustaric** [KeplerGO/KeplerScienceWebsite#68]
The Table of Contents on the DRN page is getting too long and it doesn't scroll independently from the rest of the page. As a result it can be hard to navigate the page. It seems like something better could be done, but I'm not sure what.  It is fine for now, but by the time we get to C8 or so, it might become a bother.

**Comment by barentsen** [comment]
The submenus have now been removed from the DRN table of contents to avoid it getting too long. Issue resolved!
