### ISSUE TITLE
Put C9 target list online

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#69]
Once target management is over we need to make the C9 target list. I'm opening this issue now because we have an extra proposal that we don't want to forget

ID: GO9925
PI: Barclay
Title: Two targets for engineering use during checkout

Abstract: The project needs needs to downlink three bright but unsaturated and isolated targets for downlink during the checkout phase at the start of the campaign. These targets are used to check the pointing is nominal. Only one proposed target was suitable in C9 so the project selected two additional targets: 226557170 and 225576868. These targets are assigned masks of 25x25 pixels.

Targets
225576868
226557170

**Comment by mrtommyb** [comment]
We also want a proposal description for the lagoon nebula

ID: GO9926
PI: Barclay
Title: Superaperture mask over the Lagoon nebula

**Comment by barentsen** [comment]
Noting that nearly half of the DDT targets fell inside the microlensing or lagoon superstamps, so the generation of per-proposal target lists is more complicated than usual.

**Comment by mrtommyb** [comment]
The microlensing superapertures have ID GO9001
The isolated stars should have ID GO9002
The dark clouds have ID GO9003

**Comment by barentsen** [comment]
The C9a late (ongoing) events have ID GO9004.

**Comment by mrtommyb** [comment]
Here is the list of DDT programs with approved targets. This list does not include programs who's targets exclusively fell into microlensing superstamp

GO9902
GO9903
GO9904
GO9906
GO9907
GO9908
GO9909
GO9910
GO9911
GO9912
GO9913
GO9914
GO9915
GO9916
GO9917
GO9918
GO9919
GO9920
GO9921
GO9922
GO9923
GO9925

**Comment by barentsen** [comment]
Here are the number of targets per DDT proposal that fell inside the final microlensing superstamp:

GO9901: 1
GO9902: 2
GO9906: 2
GO9907: 3
GO9911: 52
GO9913: 1
GO9915: 50
GO9916: 88
GO9919: 122
GO9920: 2
GO9923: 3

**Comment by barentsen** [comment]
The approved C9 DDT programs are now listed on the website.  I have made this live.

Still to do:
- add the "C9 paragraph" on the program page with a high level summary;
- link the DDT programs to specific C9 superstamp tiles (not sure how I would do that at this point);
- contact DDT PIs.

**Comment by kcolon** [comment]
DDT PIs have been contacted.

**Comment by barentsen** [comment]
@mrtommyb can you add a paragraph above the c9 target list, explaining the programs selected?

**Comment by barentsen** [comment]
@mrtommyb Can you look into writing the explanatory paragraph above the listing of C9 observing programs?

**Comment by barentsen** [comment]
I am giving the C9b late target masks investigation ID GO9005.

**Comment by barentsen** [comment]
I've added explanatory paragraphs for C9a and C9b.
