### ISSUE TITLE
Blog about the K2 session at the summer AAS

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/KeplerScienceWebsite#70]
encourage people to submit abstracts

**Comment by mrtommyb** [comment]
if you can write this by this afternoon it will go out in today's email, if not then it will slip for a few weeks.

**Comment by kcolon** [comment]
writing it now, wanna come read?

**Comment by kcolon** [comment]
http://keplerscience.arc.nasa.gov/submit-your-abstract-to-the-k2-special-session-at-aas228.html done!

**Comment by mrtommyb** [comment]
Thanks Knicole!
