### ISSUE TITLE
Add historical publications to the website

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#73]
E.g. Borucki's early (1984) paper about finding transits.  It's not obvious to me what page we would put these on but we can think about it.

**Comment by barentsen** [comment]
It could simply be added as a "Kepler exoplanet" publication.

We can also have a separate category for "mission definition" papers. Is there a need? Would it have many papers?

**Comment by barentsen** [comment]
Possibly useful list of older papers here: http://kepler.nasa.gov/Science/ForScientists/papersAndDocumentation/papers19952006/

**Comment by barentsen** [comment]
I have added relevant historical papers from the url above to `kpub` (or at least those with an ads abstract).

Closing this issue.
