### ISSUE TITLE
Post C10 target list online

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#77]
And notify PIs!

**Comment by barentsen** [comment]
The DDT program with ID GO10906 contains 78 targets that were observed during Campaign 1 and could now be repeated in Campaign 10. (There is a narrow strip of overlap between C1 and C10.)

The PI of this program is the GO office.  Many of the targets also appear in other programs.

**Comment by barentsen** [comment]
C10 target list, including DDT programs and their proposal pdfs, are now on the website.

**Comment by kcolon** [comment]
Can we close this?

**Comment by barentsen** [comment]
I have notified the PIs via e-mail and added a blog post. We can close this issue.

Everything is go for @mrtommyb to send out an exploder.
