### ISSUE TITLE
Update K2fov with the C14-16 pointing

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#80]
use the values straight off the KACR. Then let me know and I'll push to pypi

**Comment by barentsen** [comment]
I created a PR https://github.com/KeplerGO/K2fov/pull/16 to do this.

Still to do:
- [ ] Update positions and dates on website.
- [ ] Add field graphs to website.
- [ ] Add new 'footprint files' to website.
- [ ] Write a blog post (?) or find another way to ensure users update K2fov.

**Comment by mrtommyb** [comment]
the pull request is merge d5b3a1a

**Comment by kcolon** [comment]
Can we remove this plot now? It's no longer informative.
http://keplerscience.arc.nasa.gov/images/k2/proposed-future-fields-2018.png

**Comment by kcolon** [comment]
It would also be nice to remove the duplicate comet label on this plot ... http://keplerscience.arc.nasa.gov/images/campaign_selected/field16-final.png

**Comment by barentsen** [comment]
I removed `proposed-future-fields-2018.png` as per @kcolon's recommendation.

Closing this issue as K2fov is now up to date. See #86 for tasks related to getting users to update their version of K2fov.
