### ISSUE TITLE
There is a letter 's' on the campaigns page

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#81]
There is an 's' at the top of the table http://keplerscience.arc.nasa.gov/k2-fields.html
We need to remove it.

**Comment by mrtommyb** [comment]
I can't find what's wrong. 
<img width="818" alt="screenshot 2016-06-08 17 48 22" src="https://cloud.githubusercontent.com/assets/1900573/15915799/384a0c42-2da1-11e6-96ba-9a2c3ec22bfe.png">

**Comment by barentsen** [comment]
s

Because 1e62075b600194795244569a941a044831cc3811 :smirk:
