### ISSUE TITLE
Change link on Pipeline Release Notes page

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/KeplerScienceWebsite#83]
Once Doug is back and checks in his latest version of the pipeline release notes, we should change the link that points to `KSCI-19080-001.pdf` into `KSCI-19080-002.pdf` and make the link text less obscure.

**Comment by kcolon** [comment]
and update headings and sidebar on the data release notes page as per @mrtommyb's request:

sidebar on the data release notes page is funky when it is longer than the page. I suggest we remove submenus from it

**Comment by barentsen** [comment]
Link on pipeline release notes page has been fixed.

**Comment by barentsen** [comment]
Submenus have been removed from the data release notes page by changing e.g.

`## Features and events`

into 

`<h2>Features and events</h2>`

(which is a bit of a hacky solution, unfortunately)
