### ISSUE TITLE
Add the K2 Engineering Test target list to the GO website?

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/KeplerScienceWebsite#85]
The target list is currently only available here:
https://archive.stsci.edu/missions/k2/tpf_eng/

**Comment by mrtommyb** [comment]
# 👍

**Comment by barentsen** [comment]
I have added the engineering test to the 'targets & programs' page, cf:
http://keplergo.github.io/KeplerScienceWebsite/k2-approved-programs.html#concept-engineering-test

Two questions for @mrtommyb before closing this:

1. The target list shows 1952 LC + 17 SC = 1969 targets, however there are 2079 fits files in https://archive.stsci.edu/pub/k2/tpf_eng/long_cadence/ -- are we interested in clarifying this?
2. Do you care about making the engineering target list available in the same format as the other campaigns? Right now the format is somewhat different.

**Comment by barentsen** [comment]
The mismatch between the number of fits files and the length of the target list is likely due to superstamps.  Not investigating further for now.

Closing issue.
