### ISSUE TITLE
inconsistent Capitalization On the blog Posts

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#88]
Let's decide on a style for blog post titles. 

I suggest that we capitalize only the first word and proper nouns

**Comment by dacmess** [comment]
i vote for ee cummings 
     style.

all
       lower
                      case with

odd                         spacing

--
douglas caldwell
dacmess@gmail.com

**Comment by kcolon** [comment]
That's partly because Geert and I disagree on style choices :-P 

I VOTE WE USE ALL CAPS. WE WANT TO SHOUT OUR NEWS TO THE WORLD!!

**Comment by barentsen** [comment]
tomHasDecidedWeShouldGoForCamelCase

**Comment by kcolon** [comment]
i Checked All the Blog posts and fixeD them ACCORDINGLY.
