### ISSUE TITLE
We should advertise how to subscribe to the mailing list

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/KeplerScienceWebsite#89]
Old website says:

"K2 news will be transmitted by email exploder at non-regular intervals. If you would like to receive this newsletter/blog then sign up by sending email to keplergonews-request@lists.arc.nasa.gov with the subject heading subscribe. If you would like to stop receiving the newsletter then send email to the same address with the subject heading unsubscribe."

**Comment by kcolon** [comment]
New website says:

This page provides news updates to help the scientific community propose targets for K2 and analyze Kepler and/or K2 data. These updates will be transmitted by email exploder at non-regular intervals. If you would like to receive this newsletter/blog then sign up by sending an email to keplergonews-request@lists.arc.nasa.gov <http://keplerscience.arc.nasa.gov/keplergonews-request@lists.arc.nasa.gov> with the subject heading subscribe. If you would like to stop receiving the newsletter then send email to the same address with the subject heading unsubscribe. You can also subscribe to the RSS feed <http://keplerscience.arc.nasa.gov/feeds/all.rss.xml> to receive the latest news.

**Comment by barentsen** [comment]
Because we switched to mailchimp, this issue can be closed and replaced by issue #101.
