### ISSUE TITLE
Make a table of Kepler Quarter dates

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#97]
We have a nice table for K2 Campaign dates. Having the same thing for Kepler would be useful

**Comment by mrtommyb** [comment]
we might want to look into what other things are the in the various handbooks that having available on the web would be useful.

**Comment by barentsen** [comment]
There is one here:

https://keplerscience.arc.nasa.gov/data-products.html#kepler-data-release-notes

Should we have it contain more info, or move it to a separate page?

The dates are in the DR25 release notes:

https://archive.stsci.edu/kepler/release_notes/release_notes25/KSCI-19065-002DRN25.pdf

Tables like these would be nice to have available in machine-readable form, like this but with more columns:

https://github.com/barentsen/kepler-skye/blob/master/data/kepler-quarters.csv

Should there be a kepler-tables repo?

**Comment by barentsen** [comment]
Tables to go in a `kepler-handbook-data` repo could include:
* Kepler campaign dates and numbers;
* K2 campaign dates and coordinates;
* Images from the handbooks, e.g. figures of the focal planes, ccd layout;
* Quality flags;
* Target tables?
* Index of target pixel files?
* Plots of the fields;
* PRF data?

**Comment by barentsen** [comment]
Let's make this part of the new PyKE.
