### ISSUE TITLE
Inclusiveness statement for KepSciCon site

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#98]
We should get a statement of inclusiveness/antiharassment online before the abstracts open. I think the AAS has something we could steal. Let's run it through the SOC/LOC as well before we commit to wording.

**Comment by mrtommyb** [comment]
Here is one the AAS use 
https://aas.org/policies/anti-harassment-policy

**Comment by barentsen** [comment]
I very much like the astropy code of conduct:

http://www.astropy.org/about.html#codeofconduct

But it would have to be edited to be more suitable for a conference.  We'd also have to add a social media policy, which we can borrow from AAS.

**Comment by kcolon** [comment]
Can we just say that we strongly adhere to the AAS’s Anti-Harassment Policy and link to the AAS page?  Either way sounds like something that needs to be brought up with the SOC/LOC on Thursday's meeting.

**Comment by mrtommyb** [comment]
yes, let’s bring it up. I think that we should have something on our website though.

**Comment by barentsen** [comment]
Statement has been added in meanwhile.  Closing.
