### ISSUE TITLE
add conversion from campaign numbers to proposals cycles 

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#99]
Mike Haas says

> Where can if I find which campaigns are included in which proposal review cycle?

I asked him why

>Well, I would have found it valuable last night :)
It seems like an obvious fact that should be captured somewhere….Mike

If this is useful we should add to website.

**Comment by mrtommyb** [comment]
I'm not certain it is useful. Let's discuss.

**Comment by kcolon** [comment]
This is already available here https://keplerscience.arc.nasa.gov/data-products.html#k2-data-release-notes.  Can I close this issue?
